### ISSUE TITLE
Whats the name of this icon?

### ISSUE THREAD

**Issue by alirezaafzalaghaei** [Magog64/SURU-PLUS#10]
Actually this is not an issue. I want to change KDE Plasma system tray media player icon but i cant find it in your icon pack. what's it's name?

icon:

![Image](http://up2www.com/uploads/1643Screenshot-20180718-043337.png)

**Comment by gusbemacbe** [comment]
@alirezaafzalaghaei 

I have just released officially the new version of Suru++. Officially supported for KDE. PLease switch t the new version [Suru++ 20](https://github.com/gusbemacbe/suru-plus)
