### ISSUE TITLE
Lightworks icons

### ISSUE THREAD

**Issue by gusbemacbe** [Magog64/SURU-PLUS#12]
Ciao @Magog64!

L'azienda Lightworks utilizza due icone di 4 gocce e squalo, ma preferiscono l'icona di squalo. Le Icone [`lightwork`](https://github.com/Magog64/SURU-PLUS/blob/master/apps/scalable/lightwork.svg) e [`lightworks`](https://github.com/Magog64/SURU-PLUS/blob/master/apps/scalable/lightworks.svg) (eccoli per aprirle) devono essere le stesse cose.

**Comment by gusbemacbe** [comment]
@Magog64

**Comment by Magog64** [comment]
Ok fatto!!!
