### ISSUE TITLE
Icone perdute di Kubuntu e Xubuntu

### ISSUE THREAD

**Issue by gusbemacbe** [Magog64/SURU-PLUS#12]
* **Distribution and version:** Kubuntu and Xubuntu 18.04
* **Distribution environment:**
  - [ ] Cinammon
  - [x] Gnome
  - [x] KDE
  - [ ] LXDE
  - [x] MATE
  - [x] XCFE
  - [x] Other. Name here: Unity

### Icone perdute di Kubuntu e Xubuntu

| Nome dell'app                           | Tipo d'app  | Nome dell'icona              | Descrizione                                                                                         | Referenzia                                                                                                                                                                                                       | Suggerimento                                                                                                 |
| --------------------------------------- | ----------- | ---------------------------- | --------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------ |
| Account authentication                  | GNOME       | signon-ui                    | Accedere agli account online per l'autenticazione                                                   | Senza referenzia                                                                                                                                                                                                 | Fare le icone colorate e grigie nelle cartelle actions, apps e places                                        |
| Account Wizard                          | KDE         | org.kde.accountwizard        | Esegue la procedura guidata per la creazione di account per configurare gli account di PIM.         | Senza referenzia                                                                                                                                                                                                 | Duplicare l'icona di KDE Plasma                                                                              |
| Application Finder XFCE                 | XFCE        | edit-find                    | Trova e avvia le applicazioni installate nel sistema                                                | Referenzia dell'icona grigia edit-find                                                                                                                                                                           | Fare l'icona colorata nella cartella `apps/scalable`                                                         |
| Bluetooth Adapters                      | XCFE        | blueman-device               | Impostare le proprietà degli adattori di Bluetooth                                                  | Senza referenzia                                                                                                                                                                                                 | Fare le icone colorate e grigie nelle cartelle actions, apps e places                                        |
| Bluetooth Manager                       | XFCE        | blueman                      | Gestore di Bluetooth                                                                                | Senza referenzia                                                                                                                                                                                                 | SImile all'icona di Bluetooth e fare icone colorate  grigie nelle cartelle actions, apps e places            |
| Cantor                                  | KDE         | cantor                       | Interfaccia KDE per software matematico                                                             | [Vedere l'icona](https://edu.kde.org/cantor/)                                                                                                                                                                    | Non duplicare le icone de calcolatore, ma fare un'icona di lavanga **col calcolo integrale e differenziale** |
| Catfish ricerca di file                 | XFCE        | catfish                      | Il gatto ti cerca qualsiasi nel file system                                                         | [Visualizzare l'icona](https://launchpad.net/catfish-search)                                                                                                                                                     | Vedi la referenzia                                                                                           |
| Compiz                                  | KDE         | compiz                       | Senza descrizione                                                                                   | Senza referenzia                                                                                                                                                                                                 | Duplicare l'icona di ccsm                                                                                    |
| Gestore di archivi Engrampa             | MATE        | engrampa                     | Crea e modifica un archivio                                                                         | [La pagina sta in italiano. Vai fino all'Engrampa per vedere la descrizione e l'icona](http://mate-desktop.org/it/)                                                                                              | Vedere la referenzia                                                                                         |
| Gestore URL del telefono di KDE Connect | KDE         | kdeconnect                   | Visualizzare informazioni sui dispositivi                                                           | [Vedere l'icona](https://sempreupdate.com.br/wp-content/uploads/2016/10/como-instalar-o-KDE-Connect-no-ubuntu-linux-mint.png)                                                                                    | Vedere la referenzia                                                                                         |
| Gigolo                                  | XFCE        | gtk-network                  | Una semplice interfaccia per connettersi a file system remoti                                       | Senza referenzia                                                                                                                                                                                                 | Duplicare l'icona di network-preferences, ma con un sistema remoto conetto                                   |
| gnuclient                               | XFCE        | gnuclient                    | Senza descrizione                                                                                   | Senza referenzia                                                                                                                                                                                                 | Duplicare l'icona di GNU Emacs, **ma con un mappa**                                                          |
| gv                                      | Qualisasi   | gv_icon                      | Visualizzatore di file Photoshop e PDF                                                              | Senza referenzia                                                                                                                                                                                                 | Mescolare le icone di Photoshop e visualizzatore di PDF, ma con uno spetto                                   |
| Impostazioni di KDE Connect             | KDE         | kdeconnect                   | Connettare e sincronizzare i dispositivi                                                            | [Vedere l'icona](https://sempreupdate.com.br/wp-content/uploads/2016/10/como-instalar-o-KDE-Connect-no-ubuntu-linux-mint.png)                                                                                    | Vedere la referenzia                                                                                         |
| Indicatore di KDE Connect               | KDE         | kdeconnect                   | Visualizzare informazioni sui dispositivi                                                           | [Vedere l'icona](https://sempreupdate.com.br/wp-content/uploads/2016/10/como-instalar-o-KDE-Connect-no-ubuntu-linux-mint.png)                                                                                    | Vedere la referenzia                                                                                         |
| Informazioni personali (mugshot)        | GNOME       | mugshot                      | Configura l'immagine del profilo e i dettagli del contatto                                          | Fare l'icona di profilo  simile al Facebook                                                                                                                                                                      | Vedere la referenzia                                                                                         |
| KOrganizer                              | KDE         | korganizer                   | Programma di calendario e di agenda                                                                 | [Visualizzare in italiano](https://userbase.kde.org/KOrganizer/it)                                                                                                                                               | Non duplicare l'icona di calendario, ma di agenda con calendario ed un pennarello                            |
| LightDM GTK+ Greeter settings           | GNOME       | lightdm-gtk-greeter-settings | Configure LightDM GTK+ Greeter                                                                      | [Visualizzare sul Github coi screenshot](https://github.com/mjun/lightdm-gtk-greeter-settings)                                                                                                                   | Vedere la referenzia                                                                                         |
| Logout                                  | GNOME       | logout_highlight             | Disconettarsi del account                                                                           | Senza referenzia                                                                                                                                                                                                 | Fare le icone colorate e grigie nelle cartelle actions, apps e places                                        |
| Menu Editor                             | Qualiasi    | menulibre                    | Aggiungere o rimuovere le applicazioni dal menu                                                     | [Vedere la descrizione e l'icona](https://bluesabre.org/projects/menulibre/)                                                                                                                                     | Vedere la referenzia                                                                                         |
| Portal                                  | XFCE        | applications-system-symbolic | Senza descrizione                                                                                   | Referenzia dell'icona grigia applications-system-symbolic                                                                                                                                                        | Fare l'icona colorata nella cartella `apps/scalable`                                                         |
| Restart                                 | GNOME       | restart_highlight            | Riavviare il computer                                                                               | Senza referenzia                                                                                                                                                                                                 | Fare le icone colorate e grigie nelle cartelle actions, apps e places                                        |
| Run Program XFCE                        | XFCE        | system-run                   | Esegue un programma                                                                                 | Referenzia dell'icona appfinder                                                                                                                                                                                  | Vedere la referenzia e fare un'icona colorata nella cartella `apps/scalable`                                 |
| SCreensaver                             | XFCE        | xscreensaver                 | Cambiare le proprietà dello screensaver                                                             | Senza referenzia                                                                                                                                                                                                 | DUplica l'icona di screensaver                                                                               |
| Shutdown                                | GNOME       | shutdown_highlight           | Spegnere il computer                                                                                | Senza referenzia                                                                                                                                                                                                 | Fare le icone colorate e grigie nelle cartelle actions, apps e places                                        |
| Snappea 3-Manifold Creator              | KDE         | snappea                      | Creare e studiare le 3-varietà iperboliche                                                          | [Vedere gli esempi di immagini](https://www.google.com/search?q=hyperbolic+3-manifolds&client=ubuntu&hs=NEt&channel=fs&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjVspLHu57bAhWKiZAKHcbQCaAQ_AUICygC&biw=1920&bih=895) | Fare l'icona di iperboliche collo sfondo di formule matematiche                                              |
| Spring Tool Suite                       | Source code | sts                          | [Vedere la descrizione in italiano sulla WIkipedia](https://it.wikipedia.org/wiki/Spring_framework) | [Vedere l'icona](https://spring.io/blog/2009/05/07/springsource-tool-suite-now-free/)                                                                                                                            | Vedere la referenzia                                                                                         |
| Super Tux                               | KDE         | supertuxkart                 | Senza descrizione                                                                                   | Senza referenzia                                                                                                                                                                                                 | Duplica l'icona già creata di Super Tux e nominala come «supertuxkart»                                       |
| TeXdoctk                                | KDE         | texdoctk                     | Documentazioni e manuali di TeX                                                                     | Senza referenzia                                                                                                                                                                                                 | Fare un'icona di un dcumento coll'icona di TexLive                                                           |
| Time and Date                           | GNOME       | time-admin                   | Modificare il sistema di tempo, zona di tempo e data                                                | Senza referenzia                                                                                                                                                                                                 | Senza suggerimento                                                                                           |
| Unity Brightness & Lock                 | Unity       | system-lock-screen           | Luminosità dello schermo e impostazioni di blocco dello schermo                                     | Senza referenzia                                                                                                                                                                                                 | DUplica l'icona di blocco dello schermo                                                                      |
| Unity Online Accounts                   | Unity       | unity-online-accounts        | Conettare i accounts online sull'Unity                                                              | Senza referenzia                                                                                                                                                                                                 | Duplica le icone di network                                                                                  |
| Unity Sound Panel                       | Unity       | unity-sound-panel            | Cambiare il volume del suono e gli eventi sonori                                                    | Senza referenzia                                                                                                                                                                                                 | Duplica l'icona di volume di suono                                                                           |
| Users and Group                         | GNOME       | config-users                 | Aggiungere e rimouvere gli utenti e gruppi                                                          | Senza referenzia                                                                                                                                                                                                 | Senza suggerimento                                                                                           |
| Visualizzatore Documenti Atril          | MATE        | atril                        | Visualizza documenti multi-pagina                                                                   | Senza referenzia                                                                                                                                                                                                 | SImile all'icona di visualizzatore di documenti                                                              |
| xvkbd                                   | XFCE        | xvkbd                        | Tastiera virtuale                                                                                   | Senza refenzia                                                                                                                                                                                                   | Duplicare l'icona di tastiera                                                                                |

### Collezzione di giochi di puzzle

Vedi la lista di puzzles colle sue icone, ma io ti fornierò i nome delle icone:

https://www.chiark.greenend.org.uk/~sgtatham/puzzles/

**Nome dell'app = nome dell'icona**
* Black Box = sgt-blackbox
* Bridges = sgt-bridges
* Cube = sgt-cube
* Dominosa = sgt-dominosa
* Fifteen = sgt-fifteen
* Filling = sgt-filling
* Flip = sgt-flip
* Flood = sgt-flood
* Galaxies = sgt-galaxies
* Guess = sgt-guess
* Inertia = sgt-inertia
* Keen = sgt-keen
* Launcher = sgt-launcher
* Lightup = sgt-lightup
* Loopy = sgt-loopy
* Magnets = sgt-magnets
* Map = sgt-map
* Mines = sgt-mines
* Net = sgt-net
* Netslide = sgt-netlside
* Palisade = sgt-palisade
* Pattern = sgt-pattern
* Pearl = sgt-pearl
* Pegs = sgt-pegs
* Range = sgt-range
* Rect = sgt-rect
* Samegame = sgt-samegame
* Signpost = sgt-signpost
* Singles = sgt-singles
* Sixteen = sgt-sixteen
* Slant = sgt-slant
* Solo = sgt-solo
* Tents = sgt-tents
* Twiddle = sgt-twiddle
* Towers = sgt-towers
* Tracks = sgt-tracks
* Undead = sgt-undead
* Unequal = sgt-unequal
* Unruly = sgt-unruly
* Untangle = sgt-untangle

* **Screenshots**
Ciao @Magog64 

![image](https://user-images.githubusercontent.com/2257024/40490613-5e6b8ce6-5f42-11e8-9eb0-3ae8c1b780a7.png)

![image](https://user-images.githubusercontent.com/2257024/40490654-813e90c4-5f42-11e8-8121-ec5be5dc8eea.png)

![image](https://user-images.githubusercontent.com/2257024/40490672-8b7cab48-5f42-11e8-977a-6b951c9cb7b1.png)

![image](https://user-images.githubusercontent.com/2257024/40490685-96372fae-5f42-11e8-8b79-9a58d4ff89b7.png)

![image](https://user-images.githubusercontent.com/2257024/40490702-a1db9a3e-5f42-11e8-9899-72109844cf88.png)

![image](https://user-images.githubusercontent.com/2257024/40490711-ae4f3046-5f42-11e8-8213-0661cd363d54.png)

![image](https://user-images.githubusercontent.com/2257024/40490732-b871e1d6-5f42-11e8-87ef-9c77540c5f6d.png)

![image](https://user-images.githubusercontent.com/2257024/40490746-c05c660a-5f42-11e8-8acd-277789cf0991.png)

![image](https://user-images.githubusercontent.com/2257024/40490758-c969d84a-5f42-11e8-9eff-f7214444eabe.png)

**Comment by Magog64** [comment]
ho aggiunto la cartella SCALABLE in ACTIONS


Added Icons:

sgt-blackbox
sgt-bridges
sgt-cube
sgt-dominosa
sgt-fifteen
sgt-filling
sgt-flip
sgt-flood
sgt-galaxies
sgt-guess
sgt-inertia
sgt-keen
sgt-lightup
sgt-loopy
sgt-magnets
sgt-map
sgt-mines
sgt-netlside
sgt-net
sgt-palisade
sgt-pattern
sgt-pearl
sgt-pegs
sgt-range
sgt-rect
sgt-samegame
sgt-signpost
sgt-singles
sgt-sixteen
sgt-slant
sgt-solo
sgt-tents
sgt-towers
sgt-tracks
sgt-twiddle
sgt-undead
sgt-unequal
sgt-unruly
sgt-untangle

non ho trovato
Launcher = sgt-launcher

**Comment by gusbemacbe** [comment]
All icons fixed and added. Closed.
