### ISSUE TITLE
org.gnome.Geary

### ISSUE THREAD

**Issue by Feichtmeier** [Magog64/SURU-PLUS#13]
* **Distribution and version:**
* **Distribution environment:**
  - [ ] Cinammon
  - [x] Gnome
  - [x] KDE
  - [ ] LXDE
  - [ ] MATE
  - [ ] XCFE
  - [ ] Other. Name here: 

* **Missed icons:**
  * App name:
  * App type:
    - [ ] Flatpak
    - [ ] Native Debian package
    - [ ] Snap
    - [ ] Source code
  * Icon name (copy "`Icon=...`"): org.gnome.Geary
  * Description (copy "`Comment=...`"): : use mail-app icon from suru
  * Reference : 

* **Screenshots**

* **Additional information:**

There is an icon for "geary" but not for "org.gnome.Geary" that's the new convenience for naming apps in gnome I think =D At least they do it everywhere, no idea why but yeah - that's what happening :) Keep up the good work and thanks for providing those additional suru icons!

**Comment by gusbemacbe** [comment]
@Magog64, vedila! 

@Feictmeier, Andrea will add this night and update. He is at work now.

**Comment by Magog64** [comment]
Hi Feichtmeier thanks for the report and support, I added the org.gnome.Geary icon

**Comment by Feichtmeier** [comment]
Thanks thatwas fast

**Comment by gusbemacbe** [comment]
As it is solved and the icon is added, closes.
