### ISSUE TITLE
Please remove Haguichi application icons

### ISSUE THREAD

**Issue by ztefn** [Magog64/SURU-PLUS#14]
Since [version 1.4.0 released on May 10th](https://www.haguichi.net/news/release140/), Haguichi ships very beautiful Suru icons of its own on Ubuntu:

![Haguichi Suru Icon](https://raw.githubusercontent.com/ztefn/haguichi/master/data/icons/Suru/256x256/apps/haguichi.png)

This icon is perfected by the one and only Sam Hewit himself and looks much better than what is present in SURU PLUS.

So please remove the Haguichi application icons from this theme so that the official icon will be inherited from the Suru theme folder.

And please also remove the symbolic application icon too, it's already installed by Haguichi in hicolor. It serves no purpose to override it.

**Comment by gusbemacbe** [comment]
HI @ztefn, I am the collaborator of this icns theme, I am going to translate what you said, into Italian for @Magog64, so his English is basic. You used the advanced words.

As for this icon, I am sure he will remove, but the problem is that Ubuntu 16.04 does not have pre-installed Suru which is pre-installed only from 18.04. 

Maybe also observe that Suru++ of @Magog64 and Sam's are totally different. 

Would you also suggest me to remove the icon from my Suru++ Complete which is designed for supporting many non-Ubuntu distributions, like Arch Linux, Manjaro, etc.?

But I will maintain the icons of Haguichi in Suru++ Asprómauros (it is a monochromatic icons theme) and in Suru++ Telinkrin (desaturated blue icons theme). If you insist they be removed, let me know.

**Comment by gusbemacbe** [comment]
Ciao @Magog64, lui ti suggerisce di eliminare le icone ed icone simbolici (`-symbolic`) di Haguichi del tuo pacchetto di icone, perché Sam ha già fornito la nuova icona di Haguichi allo stilo di Suru per gli sviluppatori di Haguichi.

**Comment by Magog64** [comment]
ho sostituito l'icona di haguichi con quella di Sam!! la symbolic l'ho lasciata per non andare fuori tema!!!

**Comment by ztefn** [comment]
@gusbemacbe

Ubuntu 16.04 is not very important, because in the README.md it's stated that this theme is focused on Ubuntu 18.04.

For Suru++ Complete I think it's okay to keep the current icons or update them from the [original source](https://github.com/ztefn/haguichi/blob/master/data/icons/suru-source.svg). However, the original icons are GPLv3 licensed, while Suru++ Complete is **L**GPLv3.

Suru++ Asprómauros is no problem.

Regarding Suru++ Telinkrin, the application icon is [not blue](https://github.com/gusbemacbe/suru-plus-telinkrin/blob/25ecbee2e57bc4d1614caf1d305a3d365c7b56fb/apps/scalable/haguichi.svg)...?

**Comment by ztefn** [comment]
Correction, the [original svg source](https://github.com/ztefn/haguichi/blob/master/data/icons/suru-source.svg) itself is [Creative Commons BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/) licensed which should be sufficiently compatible with LGPLv3. So yes indeed, you can include Sam's icon in your theme.

**Comment by gusbemacbe** [comment]
Hallo @ztefn,

Ik zag dat u uit Nederland bent. Dan zal ik met u het Nederlands spreken. 

@Magog64 zegt dat hij zijn oude icoon voor uw nieuwe icoon vervangen heeft. 

Wat betreft het terminalcommando `ln -s`, het is slecht want het creëert de gebruikersnaam en het absolute pad/weg van de map, wat veroorzaakt de dood van de symlink's en ook de iconen om te gaan gemist op de andere gebruikers van de andere computers. 

> For Suru++ Complete I think it's okay to keep the current icons or update them from the original source. However, the original icons are GPLv3 licensed, while Suru++ Complete is LGPLv3.

Ah, dank u voor het foutje van de licentie te wijzen, de README van mijn Suru++ Complete is een beetje verouderd. Eigenlijk is het GPL3 sinds wanneer heeft @paulxfce me om voor GPL3 te vervangen gesuggereerd. Is het compatibel met CC BY-SA 4.0?

Nu werk ik met de alfa versie van Suru++ waarvan de doelen zijn om alle iconen bug-vrij te werden en compatibele met KDE et XFCE te werden, want sommigen van originele iconen van Sam en @Magog64 zijn niet compatibele met KDE et XFCE. @Magog64 is alleen een designer en niet programmeur, dan kan hij niet de fouten oplossen, hij heeft de verantwoordelijkheid van Suru++ Complete naar mij overgedragen. 

> Regarding Suru++ Telinkrin, the application icon is not blue...?

Dank u weer voor andere foute te wijzen. Ik heb het getekend, maar heb ik niet het bewaard. Wanner zal ik klaar met de alfa versie de Suru++ zijn, zal ik de iconen van Haguichi op Suru++ Complete en Telinkrin thema's voor uw nieuwe iconen bijwerken.

**Comment by ztefn** [comment]
@gusbemacbe Yes, I'm Dutch. Nevertheless, I learned to communicate in English because it's one of the most important languages in the world, especially in (free) software development. Best way to learn is to just start using it.

> Is GPL3 compatibel with CC BY-SA 4.0?

According to Creative Commons, CC BY-SA 4.0 [is one-way compatible](https://creativecommons.org/2015/10/08/cc-by-sa-4-0-now-one-way-compatible-with-gplv3/) with GPL3. This means you can distribute CC BY-SA 4.0 icons as GPL3, but not the other way around.
