### ISSUE TITLE
Rimouvere molte icone di memtypes

### ISSUE THREAD

**Issue by gusbemacbe** [Magog64/suru-plus#15]
Ciao @Magog64,

IO ho finito 75% del progetto di Suru++ Alfa (per KDE e molte distribuzioni). Io stavo studiando le icone di mimetype e ho fatto una ricerca di lista di mimetypes.

Molte icone non sono considerate parte di lista di mimetypes validi d'accordo con la lista di tipo associazione sull'articolo di sviluppatori di KDE. Il site di IANA anche non considera queste icone como parti di mimetypes.

Rimuovere queste icone inutili delle cartelle `16`, `24`, `scalable` e `symbolic` della cartella `mimetypes`:

* Tutte le icone di libreoffice-*
* Tuttle le icone di office-*

- application-x-appliance
- audiobook
- audio-x-smart-playlist
- authors
- binary
- calamares
- calligrasheets
- calligrawords
- document
- exec
- extension
- fluid
- git-cola
- gnome-package
- gtk-file
- im.vector
- image
- internet-archive
- internet-telephony
- kaffeine
- kalgebra
- kalgebrabackend
- kamoso
- kchart
- kdiamond
- kile
- kipi-panorama
- kiriki
- kjumpingclube
- kleopatra
- kmenuedit
- kmousetool
- kolourpaint
- kpat
- kspread
- ktnef
- kube-mail
- kword
- last.fm
- library-audiobook
- mail-client
- model
- photolayoutseditor
- plasma-media-center
- plasma-mobile-phone
- podcast
- presentation
- rss
- ruby
- sh
- sheets
- shellscript
- source-playlist
- source-smart-playlist
- spreadsheet
- subtitlecomposer
- systemsettings
- utilities-energy-monitor
- word
- wordprocessing

**Comment by Magog64** [comment]
audiobook, internet-archive, last.fm - servono per player Banshee

per quale motivo dobbiamo eliminare queste icone?
Tutte le icone di libreoffice-*
Tuttle le icone di office-*

**Comment by gusbemacbe** [comment]
Ciao @Magog64 

Perché internet-archive e last.fm non stano nella lista di mimetypes. Nei temi di icone Numix e Papirus, queste icono nono presenti. L'applicazione KDE System Settings anche mostra la lista di mimetypes in cui queste icone non ci sono. 

Adesso io ho visto nuovamente la lista di icone di mimetypes nel tema di Numix. Scusami, io stavo molto sbagliato. E rimette le icone di libreoffice-* e libreoffice-oasis-*. Rimette solo poche icone: 

* audiobook.svg
* authors.svg
* binary.svg
* document.svg
* exec.svg
* extension.svg
* gnome-package.svg
* gtk-file.svg
* image.svg
* model.svg
* wordprocessing.svg

Ma rimette solo 4 icone office-* e 5 icone di openoffice*:

* office-contact
* office-document
* office-illustration
* office-spreadsheet
* openofficeorg3-database
* openofficeorg3-drawing
* openofficeorg3-extension
* openofficeorg3-oasis-database
* openofficeorg3-oasis-spreadsheet	

Vedi la lista completa di mimetypes e fai tutte le icone non incluse: [Clicca per vedere la cartella `mimetypes` di Numix](https://github.com/numixproject/numix-icon-theme/tree/master/Numix/64/mimetypes).

Anche hai bisogna di migliore molto la cartella `places`, perché molte icone non sono considerate tipi di cartella, per esempio, applications-*. Compara la tua cartella `places` a quella di Numix, visita [(clicca qui per vedere la lista di icone di places di Numix)](https://github.com/numixproject/numix-icon-theme/tree/master/Numix/64/places) e fa una grande pulizia di icone.

* fare solo le icone di calendar-*
* fare solo le icone nel seguito:
   * desktop
   * distributor-logo
   * edittrash
   * emptytrash
   * fileopen
   * folder-*
   * gnome-*
   * gtk-directory
   * gtk-network
   * inode-directory
   * internet-radio
   * library-*
   * mail-*
   * neat
   * network-*
   * nfs
   * novel-button
   * other-desktop
   * redhat-network-server
   * redhat-system-group
   * samba
   * server
   * start-here
   * stock_*
   * trashcan_empty
   * trashcan_full
   * user-*
  
* Non fare le icone di xfce-* perche loro non parti di Ubuntu. 
* Non fare tutte le altre icone in quella lista di icone di `places` di Numix. Fa solo queste icone ch'i ho indicate.
