### ISSUE TITLE
Ufficiale icona

### ISSUE THREAD

**Issue by gusbemacbe** [Magog64/SURU-PLUS#25]
Ciao @Magog64 !

Il nostro contributore @ChrisP4 ti suggerisce di modificare l'icona Firefox, si rivolge a te nel *pull request* [richiesta di *pull*] perché la tua nuova icona di Firefox non è ancora ufficiale. Mozilla non decide ufficializzare le nuove icone ancora. 

Lui ha fatto e migliorato molto la nuova icona. Puoi visualizzare l'icona sul *pull request* (fa un clic in *commits*, nel file e dopo nell'icona di documento).

Se approvi, fa un clic in *merge pull request* e dpop nel *Create merge commit*.

**Comment by Magog64** [comment]
vista, se la devo preferisco la nostra vecchia icona !!

**Comment by Magog64** [comment]
Chi è ChrisP4?

**Comment by gusbemacbe** [comment]
È un nuovo contributore (non collaboratore) chi ha fatto 4 nuove icone perdute e fatto un pull request ieri qui.

**Comment by Magog64** [comment]
ok
decidi anche tu
io o il nuovo logo o la nostra vecchia icona !!

**Comment by gusbemacbe** [comment]
Il repositorio è tuo. Come tu preferisci la vecchia icona, noi decidemmo mantenere la  vecchia icona. Per favore rinomina la tua nuova icona per firefox-new e la tua vecchia icona per firefix.

**Comment by Magog64** [comment]
a te quale piace di più?

**Comment by gusbemacbe** [comment]
La nuova icona di Chris, alla causa del bello gradiente. Non mi piace la nuova icona ridisegnata dal Mozilla perché lei mi ricorda la icona di GitLab. Vedi l'icona di GitLab: https://about.gitlab.com/.

Ma come il tuo repositorio è tradizionale e per Ubuntu, deviamo mantenere la vecchia icona e possiamo sostituire la nostra nuova icona ridesignata dal Mozilla dalla nuova icona del @ChrisP4.

**Comment by ChrisP4** [comment]
@gusbemacbe the gradients I took from the official firefox logo. They are quite nice.

Disclaimer: *(I don't know Italian)*

**Comment by Magog64** [comment]
ho reinserito la vecchia icona !!

**Comment by gusbemacbe** [comment]
Perfect!
Perfetto!

**Comment by gusbemacbe** [comment]
@ChrisP4, I reopen your PR and upgrade the repository and update your icon to `firefoxnew.svg`
