### ISSUE TITLE
Io ho creato una nuova branch chiamata `beta`

### ISSUE THREAD

**Issue by gusbemacbe** [Magog64/SURU-PLUS#26]
Ciao @Magog64!

Io ho creato una nuova _branch_/versione chiamata "`beta`" per non passare alcuno nuovo per la _branch_/versione ufficiale ("`master`") come tu mi hai chiesto. 

1. Vai alla cheda "`Code`".
2. Seleziona il pulsante "_Branch_".
3. Cambia di "`master`" per "`beta`".

Vedi il nuovo README. Se te piace, bene. Ma scarica la versione beta e testala. 

Io ho sostituito le cartelle 24 e 32 per le cartelle simboliche (_symlinks_) per economizzare la dimensione del tuo repositorio. 

Se stai di accordo, io vado fondere la _branch_ "beta" nella _branch_ "master". 

Io sto aspettando la tua approvazione. 

Se vuoi utilizzare i _symlinks_, per favore utilizzare il Dolphin. Nautilus è malo per creare i _symlinks_.

**Comment by Magog64** [comment]
![schermata da 2018-09-08 09-05-19](https://user-images.githubusercontent.com/7957697/45251608-45cf5400-b349-11e8-9a70-3aed909c9036.png)
come puoi vedere su Banshee mancano due piccole icone che erano nella master version
source-smart-playlist
source-playlist
una volta aggiunte puoi mettere "MASTER"

**Comment by Magog64** [comment]
per il mio uso personale ho fatto i symlinks anche per "categorie" "mimes" , "device" e "places" prova a inserirle

**Comment by gusbemacbe** [comment]
Le icone source-smart-playlist e source-playlist sono per la cartella "apps"?

**Comment by Magog64** [comment]
io le ho nella cartella places 16, penso che non sia importante la collocazione

**Comment by gusbemacbe** [comment]
Ah, io ho queste due icone nel mio repositorio, io vado copiarle per il tuo repositorio. Loro sono dalla cartella "actions".

**Comment by Magog64** [comment]
ok

**Comment by gusbemacbe** [comment]
Hai perduto molte icone nella cartella "actions", non solo queste due icone. Non ti preoccupare, io utilizzo Meld per copiare le icone perdute per il tuo repositorio e passare per la branch beta.

**Comment by gusbemacbe** [comment]
La versione master ha 94MB.
La versione beta ha 81MB.
Economizzando 13MB. Molto buono?

**Comment by gusbemacbe** [comment]
@Magog64, io sto aspettando la tua approvazione.

**Comment by Magog64** [comment]
Certo fai pure

Il dom 9 set 2018 23:27 Gustavo Reis <notifications@github.com> ha scritto:

**Comment by gusbemacbe** [comment]
Grazie, @Magog64. Pronto. Io ho aggiornato anche la tua descrizione nuova sull'OpenDesktop. Io aspetto chi la nuova descrizione ti piaccia.
