### ISSUE TITLE
Icone perdute di applicazioni installate via Flatpak

### ISSUE THREAD

**Issue by gusbemacbe** [Magog64/suru-plus#29]
Ciao @Magog64 

Ecco le liste di icone perdute di applicazioni installate da Flatpak:

* LibreOffice Base - `org.libreoffice.LibreOffice-bas`e
* LibreOffice Calc - `org.libreoffice.LibreOffice-calc`
* LibreOffice Draw - `org.libreoffice.LibreOffice-draw`
* LibreOffice Impress - `org.libreoffice.LibreOffice-impress`
* LibreOffice Math - `org.libreoffice.LibreOffice-math`
* LibreOffice Writer - `org.libreoffice.LibreOffice-writer`
* LibreOffice - `org.libreoffice.LibreOffice-startcenter`
* Slack - `com.slack.Slack`
* Telegram - `org.telegram.desktop`

Per Popcorn-Time, purtroppo l'utente non mi ha risposto. Ma io ho analizzato i file binari di quest'applicazione. Sul file binario, lui non ha icona né file di configurazione di desktop. Sul pacchetto di Debian, ciò è `butter`, il nome dell'icona.

**Comment by gusbemacbe** [comment]
Quando fatto, non dimenticare di muovere la carta di "Facendo" per "Fatto" sul Project:

https://github.com/Magog64/suru-plus/projects/1

**Comment by gusbemacbe** [comment]
Sull'altro file binario, c'è altro nome dell'icona di PopCorn Time, ciò è `popcorntime-ce`.

**Comment by Magog64** [comment]
ok fatto!! 

cosa devo muovere?

**Comment by gusbemacbe** [comment]
Trascina la carta da una colonna e rilascia la carta in un'altra colonna

**Comment by gusbemacbe** [comment]
Vedi l'esempio:

![esempio](https://user-images.githubusercontent.com/2257024/46237130-09e04b00-c359-11e8-9a0c-a12c8f4e01e3.gif)

**Comment by Magog64** [comment]
fatto
