### ISSUE TITLE
@Magog64, please remove me from collaborator list. 

### ISSUE THREAD

**Issue by gusbemacbe** [Magog64/SURU-PLUS#3]
@Magog64,

Please remove me from collaborator list. Even if you are not a programmer, you may get by, face and deal with the bugs and the issues. The Linux users want only you to solve instead of me. Please, do not ask me to help you because the Linux users will not approve it.

Per favore rimouvermi della lista di collaboratori. Sebbene tu non sii un programmatore, devi arrangiarti, affrontare e tratare coi bug e coi problemi. Gli utenti di Linux vogliono che soltanto tu risolvi al invece di me. Per favore, non mi chiedere di aiutarti perché gli utenti di Linux non approvaranno.

**Comment by Magog64** [comment]
Gustavo, non mi interessa chi vogliono gli utenti, io voglio che tu rimanga nel progetto perché tu sei stato il motore, senza il tuo aiuto non avremmo fatto tutto questo, in ubuntu ogm gli utenti preferiscono il nostro set all'originale !! https://www.omgubuntu.co.uk/2018/06/ubuntu-suru-icon-theme-extends-coverage-to-more-filetypes, ti prego rimani!!

**Comment by gusbemacbe** [comment]
OK, come tu vuoi ch'io rimana, fermato.
