### ISSUE TITLE
[Missing] VeraCrypt Icon

### ISSUE THREAD

**Issue by ntilotta** [Magog64/suru-plus#32]

**Comment by gusbemacbe** [comment]
Ciao @ntilotta !

Senza dettagli, sarà sapere quale il nome dell'icona e come hai installato. Per favore, va al `/usr/share/applications/` o `tuo_nome/.local/share/applications` e apri i file desktop di applicazioni cui icone sono perdute, con il tuo editore di testo. Copiare `Icon=` ici. 

Osserva che se la tua distribuzione non è Ubuntu, poi non offriremo il supporto per le distribuzione non-Ubuntu.

**Comment by Magog64** [comment]
Added

**Comment by gusbemacbe** [comment]
Ready
