### ISSUE TITLE
[Missing] Tor Browser Icon

### ISSUE THREAD

**Issue by ghost** [Magog64/suru-plus#33]

**Comment by gusbemacbe** [comment]
Ciao @ntilotta !

Senza dettagli, sarà sapere quale il nome dell'icona e come hai installato. Per favore, va al `/usr/share/applications/` o  `tuo_nome/.local/share/applications` e apri i file desktop di applicazioni cui icone sono perdute, con il tuo editore di testo. 

Osserva che anche abbiamo già una icona di Tor Browser: https://github.com/Magog64/suru-plus/blob/master/apps/scalable/tor-browser.svg

Osserva che se la tua distribuzione non è Ubuntu, poi non offriremo il supporto per le distribuzione non-Ubuntu. 

Più una cosa: non sopportiamo gli app installati via snap.
