### ISSUE TITLE
[Missing] Electrum Bitcoin Wallet Icon

### ISSUE THREAD

**Issue by ntilotta** [Magog64/suru-plus#34]

**Comment by gusbemacbe** [comment]
Ciao @ntilotta !

Senza dettagli, sarà sapere quale il nome dell'icona e come hai installato. Per favore, va al `/usr/share/applications/` o  `tuo_nome/.local/share/applications` e apri i file desktop di applicazioni cui icone sono perdute, con il tuo editore di testo. Copiare `Icon=` ici.

**Comment by gusbemacbe** [comment]
@ntilotta, senza risposte, sarà molto difficile.

**Comment by Magog64** [comment]
Added

**Comment by gusbemacbe** [comment]
Ready
