### ISSUE TITLE
PyCharm icon request

### ISSUE THREAD

**Issue by dimgrav** [Magog64/suru-plus#35]
A PyCharm Icon would be most welcome! :)

**Comment by Magog64** [comment]
Hi dimgrav ho caricato la tua icona 
per le prossime richieste vai al /usr/share/applications/ o tuo_nome/.local/share/applications e apri i file desktop di applicazioni cui non ci sono le icone con il tuo editore di testo. Copiare Icon= ici.

**Comment by dimgrav** [comment]
Grazie mille!

**Comment by gusbemacbe** [comment]
@Magog64 

Non dimenticare aggiungere le icone di PyCharm installato via flatpak. Ecoo le icone:

* `com.jetbrains.PyCharm-Community`
* `com.jetbrains.PyCharm`
* `com.jetbrains.PyCharm-Professional`

**Comment by gusbemacbe** [comment]
@dimgrav 

We did not know how you installed PyCharm, but all the icons have just been added.

When you do next icon request, do not forget of saying how you installed. It will be easy for our work.

**Comment by dimgrav** [comment]
Hi @gusbemacbe 

I use PyCharm Professional, always installed from the JetBrains website packages and not from any package manager.

I installed the icons in `~/.local/.icons` (not in `/usr/share/icons`) and changed the `Icon` path of the PyCharm launcher to `pycharm`.

Thanks for the super fast feedback, hope this helps.

**Comment by dimgrav** [comment]
Hi @gusbemacbe 

I use PyCharm Professional, always installed from the JetBrains website packages and not from any package manager.

I installed the icons in `~/.icons` (not in `/usr/share/icons`) and changed the `Icon` path of the PyCharm launcher to `pycharm`.

Thanks for the super fast feedback, hope this helps.

**Comment by gusbemacbe** [comment]
Hi @dimgrav !

Παρακαλώ! (I speak Greek)

Yes, snap-built and source-code-built apps are hard-coded. If you plan to install a snap-built app, here are steps:

```shell
sudo cp /var/lib/snapd/desktop/applications/*.desktop ~/.local/share/applications
sudo chmod -R 777 ~/.local/share/applications
# For removing the duplicates
sudo rm /var/lib/snapd/desktop/applications/*.desktop
```

* Go to `~/.local/share/applications`.
* Open each desktop file of snap-built app with text editor and modify the `Icon` path as you have already done and know. 

Log out or reboot or refresh the session

**Comment by dimgrav** [comment]
Good to know, it may come in handy in the future.

Obrigado!
