### ISSUE TITLE
[Missing] DBeaver icon

### ISSUE THREAD

**Issue by vincentvanvugt** [Magog64/suru-plus#36]
Exec=/usr/share/dbeaver/dbeaver
Icon=/usr/share/dbeaver/dbeaver.png

[https://dbeaver.io/download/](https://dbeaver.io/download/)

**Comment by gusbemacbe** [comment]
Hello @vincentvanvugt 

@Magog64 will add soon it.

Change ` Icon=/usr/share/dbeaver/dbeaver.png` to ` Icon=dbeaver`
