### ISSUE TITLE
[Missing] GitKraken icon

### ISSUE THREAD

**Issue by vincentvanvugt** [Magog64/suru-plus#37]
Exec=/usr/share/gitkraken/gitkraken
Icon=app

[https://www.gitkraken.com/download](https://www.gitkraken.com/download)

Grazie mille!

**Comment by gusbemacbe** [comment]
@Magog64 , io andava fare le icone, ma maledetto Arch mi forzava a fare upgrade. Hai già aggiungo. Io vado fermare gli issue.
