### ISSUE TITLE
Any chance to include recent mime types from original suru icon set

### ISSUE THREAD

**Issue by VandaLHJ** [Magog64/suru-plus#4]
Do you plan to keep current, or you'll include sam's icons?

**Comment by gusbemacbe** [comment]
@Magog64 is always including the next Sam's icons.

**Comment by VandaLHJ** [comment]
Ok, but for example mimetypes 32 are using grayscale icons instead of fullblown color icons (like in original suru theme).

**Comment by gusbemacbe** [comment]
Ah, he is keeping the current mimetypes icons. 

If you want the icons to be coloured at 32px, you can modify and replace the size in the `index.theme` and change the size of size minimum and maximum of `[mimetypes/scalable]`.

**Comment by gusbemacbe** [comment]
@VandaLHJ 

As I have promised you I would solve your need. I have just released the new version of Suru++ with all new and redesigned 1k mimetypes icon. The folder 32 is officially colourful. Please visit [Suru++ 20](https://github.com/gusbemacbe/suru-plus). I hope you like the new version and enjoy the new mimetype icons.
