### ISSUE TITLE
R studio icon request. 

### ISSUE THREAD

**Issue by haseebmahmud** [Magog64/suru-plus#40]
Could you please include a [RStudio icon](https://www.rstudio.com/about/trademark/) in the pack? 
Thanks in advance. Appreciating your great work.

**Comment by gusbemacbe** [comment]
Hello @haseebmahmud !

The [RStudio](https://github.com/Magog64/suru-plus/blob/ff3f5c3d5c9a0f3b8a2bc29549f6c14838e69177/apps/scalable/rstudio.svg) icon added.
