### ISSUE TITLE
Non cambiare l'icona di «desktop»!

### ISSUE THREAD

**Issue by gusbemacbe** [Magog64/suru-plus#46]
Ciao @Magog64 !

Per favore, ritorna l'antica icona di «desktop»!

Perché «desktop» è per la cartella di desktop e per il desktop del sistema operativo.

Gli sviluppatori di GitHub Desktop hanno già risolto di cambiare il nome dell'icona di «desktop» per «github-desktop».

**Comment by Magog64** [comment]
ok fatto

**Comment by gusbemacbe** [comment]
Ottimo e grazie mille!
