### ISSUE TITLE
[Missing Mimetype] PureScript

### ISSUE THREAD

**Issue by ntilotta** [Magog64/suru-plus#47]
Official Website: http://www.purescript.org/
File extensions: .purs

**Comment by gusbemacbe** [comment]
This is the third extension that Linux does not support yet. 

ELM, Nim and PureScript are not present in the file associations list at Manjaro KDE. 

If not, maybe you have to add and create x-elm, x-nim and x-purs, like:

![image](https://user-images.githubusercontent.com/2257024/50499543-7ee31f80-0a31-11e9-8a8a-466e7a33d368.png)

But I am waiting for the answer of @SmartFinn.

**Comment by gusbemacbe** [comment]
I have tested, creating new extension and it worked. But you use GNOME and I do not know how to create the new extension. Let's wait for the answer of @SmartFinn, he is an experienced programmer. As these extensions are not supported yet, the programmers who use this icons theme have to create by themselves. 

![image](https://user-images.githubusercontent.com/2257024/50499659-91aa2400-0a32-11e9-8a6b-515dd5be8c77.png)

**Comment by gusbemacbe** [comment]
KDE develoeprs: @rwha and @cfeck, @Montel, @davidedmundson,
@Pointedstick

GNOME developers: @averi, @behdad, @cgwalters and @SEJeff

Good evening, please consider adding support for ELM, Nim and PureScript programming languages as new files associations if possible. They are becoming popular, principally ELM.

**Comment by gusbemacbe** [comment]
Now, in the commit 3a7ee64, PureScript mimetype is added.

Wait for the answer of @SmartFinn, he will test it and tell you how you create in GNOME.

**Comment by ntilotta** [comment]
@gusbemacbe okay, thank you so much!

**Comment by gusbemacbe** [comment]
@SmartFinn, sorry, I found something, but I am not sure it will work on Gnome, maybe @ntilotta , you can try and test.

I found where the ELM ffile asocitaion I created is stored. It is in `~/.local/share/mime/`

Run via terminal:

```
touch ~/.local/share/mime/text/x-elm.xml
touch ~/.local/share/mime/icons
nano ~/.local/share/mime/text/x-elm.xml
```

Copy

```
<?xml version="1.0" encoding="utf-8"?>
<mime-type xmlns="http://www.freedesktop.org/standards/shared-mime-info" type="text/x-elm">
  <!--Created automatically by update-mime-database. DO NOT EDIT!-->
  <comment>ELM Programming Language</comment>
  <icon name="x-elm"/>
  <glob-deleteall/>
  <glob pattern="*.elm"/>
</mime-type>
```

And modify the file `icons` via the command `nano ~/.local/share/mime/icons`

```
x-elm
```

Log out and log in

**Comment by gusbemacbe** [comment]
Great! I close now.

**Comment by Pointedstick** [comment]
Ideally this would be added to `shared-mime-info` so individual desktop environments wouldn't have to redundantly add support themselves.

https://www.freedesktop.org/wiki/Specifications/shared-mime-info-spec/

**Comment by gusbemacbe** [comment]
@Pointedstick 

I read, but I do not understand. Are you suggesting us to submit an enhancement request to the MIME bugtracker with our new missed XML files that we have created?

**Comment by Pointedstick** [comment]
Yes.
