### ISSUE TITLE
[Missing Mimetype] Elm Programming Language

### ISSUE THREAD

**Issue by ntilotta** [Magog64/suru-plus#48]
Official Website: https://elm-lang.org/
File extensions: .elm

Tip: https://github.com/PKief/vscode-material-icon-theme/blob/master/icons/elm.svg

**Comment by gusbemacbe** [comment]
Linux does not support this programming language, as this is very new language.

I must ask to @SmartFinn about it. 

@SmartFinn, did you add mimetypes elm and nim in your Papirus icons?

I checked the list of file asociations, elm and nim files are not listed.

**Comment by ntilotta** [comment]
@gusbemacbe I know that Linux doesn't support those mime types yet, I'm asking if it was possible to add them, I'll add those mime types manually on my distributions for now, waiting until they will be officially supported, thanks.

**Comment by gusbemacbe** [comment]
Added ELM mimetype (1e2e20e).
