### ISSUE TITLE
Missing icons: Remmina Remote Desktop Client

### ISSUE THREAD

**Issue by VandaLHJ** [Magog64/SURU-PLUS#5]
Hi, 

Any chance to add this one to the icon set?

**Comment by Magog64** [comment]
yes, what is the name of the icon?

**Comment by Magog64** [comment]
the name is org.remmina.Remmina, I have already loaded in the set, confirm the solution of the problem

**Comment by gusbemacbe** [comment]
@Magog64, ma hai aperto il file col Gedit e hai visto `Icon=...`?

**Comment by Magog64** [comment]
no, I looked here https://github.com/FreeRDP/Remmina

**Comment by VandaLHJ** [comment]
I'm using .deb

**Comment by gusbemacbe** [comment]
@VandaLHJ 

OK, Debian apps can change the icon when icons theme is applied. But we need to know the icon name. Please check the desktop file of Remmina Remote to make sure that @Magog64 solved your problem.

**Comment by VandaLHJ** [comment]
[Desktop Entry]
Name=Remmina Remote File
Comment=Access remote desktops with Remmina
Exec=/usr/bin/remmina --connect %U
Icon=org.remmina.Remmina
Terminal=false
Type=Application
StartupNotify=true
MimeType=application/x-remmina;
NoDisplay=true

**Comment by gusbemacbe** [comment]
The, @Magog64 has solved your problem. He has just added the icon now. You can upload the icons theme now.
