### ISSUE TITLE
Icone perdute

### ISSUE THREAD

**Issue by gusbemacbe** [Magog64/suru-plus#50]
Ciao @Magog64 !

Come stai?

Ecco le icone perdute:

| Nome | Icon | Site| Nome dell'icona |
| --- | --- | ---| --- |
| Fluid | ![fluid](https://user-images.githubusercontent.com/2257024/50810693-082c0900-12f2-11e9-8b2f-00c46988a32f.png) | sconosciuta | fluid.svg |
| fman | ![fman](https://user-images.githubusercontent.com/2257024/50810762-71ac1780-12f2-11e9-9313-5788b496f45d.png) | https://fman.io/ | fman.svg |
| fofix | ![fofix](https://user-images.githubusercontent.com/2257024/50810815-ad46e180-12f2-11e9-93a3-f6fd2289b445.png) | https://github.com/fofix/fofix | fofix.svg |
| foobillard | ![foobillardplus](https://user-images.githubusercontent.com/2257024/50810870-fa2ab800-12f2-11e9-88d7-f89263fd16a7.png) | https://github.com/alrusdi/foobillardplus | foobillardplus.svg |
| Freeciv | ![freeciv-client](https://user-images.githubusercontent.com/2257024/50810892-1890b380-12f3-11e9-9243-e11b75990407.png) | http://www.freeciv.org/download.html | freeciv-client.svg |

**Comment by Magog64** [comment]
Added icons fluid fofix fman foobillardplus freeciv-client

**Comment by gusbemacbe** [comment]
Molto bene, @Magog64 !
