### ISSUE TITLE
Icone sullo stilo di Suru++

### ISSUE THREAD

**Issue by gusbemacbe** [Magog64/suru-plus#51]
Ciao @Magog64 !

Come stai?

Per favore leggere il mio pen:

https://codepen.io/gusbemacbe/full/GPPKPx

**Comment by Magog64** [comment]
Ciao @gusbemacbe 
è un lavoro molto lungo, comunque penso di poterlo fare

**Comment by Magog64** [comment]
fatte 45 icone

**Comment by gusbemacbe** [comment]
@Magog64 

Molte grazie. Osserva che KGoldRunner, KTeaTime e Peruse sono applicazioni di KDE.

**Comment by Magog64** [comment]
ok grazie, le prime due le ho tolte

**Comment by Magog64** [comment]
ok sostituita

**Comment by gusbemacbe** [comment]
Molte grazie!
