### ISSUE TITLE
Per favore, cambia l'icona di warzone2100

### ISSUE THREAD

**Issue by gusbemacbe** [Magog64/suru-plus#52]
Ciao @Magog64 !

Come io ti ho detto che noi non possiamo utilizzare le icone di Flaticon. Flaticon può querelarti. 

Por favore, cambia l'icona di warzone2100 e crea da zero.

**Comment by Magog64** [comment]
Ok stasera quando torno a casa

Il giorno mer 23 gen 2019, 05:22 Gustavo Reis <notifications@github.com> ha
scritto:
