### ISSUE TITLE
Corriggere le icone

### ISSUE THREAD

**Issue by gusbemacbe** [Magog64/suru-plus#53]
Ciao @Magog64 

Le icone che hai disegnate sono incorrette:

| Nome   | Perché?                     | Incorretto                                                           | Corretto (mio)                                                       |
| ------ | --------------------------- | -------------------------------------------------------------------- | -------------------------------------------------------------------- |
| Mame   | Perché non è un Game Boy    | <img alt="Mame" src="https://i.imgur.com/TIk5Y1w.png" height=60px>   | <img alt="Mame" src="https://i.imgur.com/yxGKZP5.png" height=60px>   |
| Octopi | È un fantasma, non un polpo | <img alt="Octopi" src="https://i.imgur.com/Rr7g3H3.png" height=60px> | <img alt="Octopi" src="https://i.imgur.com/Z2Qm2N4.png" height=60px> |

* Copia l'icona di `recipes` per sostituire l'icona di `org.gnome.Recipes`. 
* Per favore, cambia l'icona di `desktop` come gia te l'ho detto alunci mesi fa, perché `desktop` è un _desktop_, non un'icona di GitHub.
* Cambia e migliora le icone di Github, loro sono molto brutte.

**Comment by Magog64** [comment]
Improved icons desktop github mame nemiver octopi recipes inkscape

**Comment by gusbemacbe** [comment]
Ottimo!
