### ISSUE TITLE
Insync appindicator icon is wrong again

### ISSUE THREAD

**Issue by fishears** [Magog64/SURU-PLUS#6]
Hi
I reported this in an earlier build and it was fixed... now it's back :)
The appindicator icon for Insync has reverted to being the same as the app icon rather than being the symbolic version (which includes status indication).
I see
![screenshot from 2018-05-05 10-29-45](https://user-images.githubusercontent.com/909571/42418135-1a844112-8292-11e8-9f9d-0ff5a5b7cd34.png)
but it should be
![screenshot from 2018-05-05 15-15-46](https://user-images.githubusercontent.com/909571/42418137-20604f72-8292-11e8-9e7b-495d38901e97.png)

**Comment by gusbemacbe** [comment]
Thank you for your report, we did a downgrade from the latest version to the minimal version which is optimised only for Ubuntu. We will fix it today.

**Comment by Magog64** [comment]
Hi fishears, I think I've solved it

**Comment by gusbemacbe** [comment]
@Magog64 I also pushed the icons too. But you were too quick to push before me. I am going to close it now.
