### ISSUE TITLE
Cambio Colore 

### ISSUE THREAD

**Issue by Bonandry** [Magog64/suru-plus#73]
ho installato lo script
andrea@andrea:~$ wget -qO- https://git.io/fhQdI | sh
......
=> Decomprimendo l'archivio ...
=> Eliminare Suru++ Folders ...
[sudo] password di andrea: 
=> Installando ...
=> Pulendo la cache ...
=> Fatto!

voglio le icone folder color 

andrea@andrea:~$ suru-plus-folders -C aubergine --theme Suru++-Ubuntu
suru-plus-folders: Error: Unable to find 'aubergine' color in 'Suru++-Ubuntu'

da un errore, dove sbaglio?

**Comment by gusbemacbe** [comment]
Io vado investigare, testando sul mio terminale.

**Comment by gusbemacbe** [comment]
Ho scoperto. Suru++ 25 utilizza la cartella `64` e Suru++ Ubuntu utilizza la cartella `scalable`. Vado parlare con SmartFinn.

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Ho finito i miei progetti. Ho aggiornato Suru++ Cartelle. Ho parlato con SmartFinn, egli mi ha detto che non era possibile lo script leggere i due temi che avevanno nomi differenti di `places`, perciò, ho rinominato `64` per `scalable` del mio Suru++ 30. Adesso due Suru++ 30 e Suru++ Ubuntu sono resi compatibili. 

Prova di nuovo.
