### ISSUE TITLE
[Icon Request] Visual Studio Code

### ISSUE THREAD

**Issue by leandrocodes** [Magog64/suru-plus#75]
Hey sir! How are you doing? You are making a really great job with those icons, can you make one for vscode? Is the only icon on my dock bar that doesn't have changed haha.
Congrats

**Comment by gusbemacbe** [comment]
Oi @leandrocodes!

Já temos o ícone de VSCode: https://github.com/Bonandry/suru-plus-ubuntu/blob/master/Suru++-Ubuntu/apps/scalable/visual-studio-code.svg

Como você instalou o VSCode? Via Flatpak ou Snap?

**Comment by leandrocodes** [comment]
Nenhum dos dois, baixei o .deb no site oficial do vscode
![Captura de tela de 2019-05-16 01-06-37](https://user-images.githubusercontent.com/33972169/57827833-ff9f7f80-7776-11e9-8b48-615558060ac7.png)

**Comment by Bonandry** [comment]
Hi leandrocodes, if you want it immediately go to the app / scalable folder and rename the "com.visualstudio.code" icon, I'll add it for the next release

**Comment by leandrocodes** [comment]
Can you tell me how i do that?

**Comment by Bonandry** [comment]
download here the new version that is already present

**Comment by leandrocodes** [comment]
already done, nothing changes

**Comment by gusbemacbe** [comment]
@leandrocodes !

Transfere a partir da branch `beta` e não da branch `master`. Executa o comando (como utilizas o Ubuntu):

```bash
wget -qO- https://raw.githubusercontent.com/Bonandry/suru-plus-ubuntu/master/install.sh | TAG=beta env DESTDIR="$HOME/.icons" sh
```

**Comment by gusbemacbe** [comment]
Na próxima vez, se o tema de ícones não tiver ícone do teu aplicativo favorito, sugiro o tutorial em português no meu [Suru++ 30](https://github.com/gusbemacbe/suru-plus), pois Suru++ Ubuntu ainda não tem tradução em português:

Tutorial [Aplicativos do AppImage](https://github.com/gusbemacbe/suru-plus/wiki/Aplicativos-do-AppImage) – não se aplica apenas aos aplicativos do AppImage, também aos que têm ícones predefinidos ou fixamente codificados.

**Comment by leandrocodes** [comment]
Thanks Guys! I'm love with your work.
