### ISSUE TITLE
Icon Request: Virt Machine Manager

### ISSUE THREAD

**Issue by richardsith** [Magog64/suru-plus#79]
Missing icon for Virtual Machine Manager [https://virt-manager.org/](url) it's possible to add that to suru++ ubuntu package? I love that......

Thank you for the consideration and appreciate this project very much!

**Comment by Bonandry** [comment]
Ciao Riccardo, in allegato ti ho messo un file zip, aprilo e metti l'icona corrispondente nella cartella del tuo set suru++ 
se hai problemi chiedi pure!
[apps.zip](https://github.com/Bonandry/suru-plus-ubuntu/files/7049118/apps.zip)

**Comment by richardsith** [comment]
Ciao,
tutto funzionante...... 
Ti faccio i complimenti perchè è il pack di icone più bello in assoluto!!!Grazie.

Buon lavoro e buona gironata
