### ISSUE TITLE
Bug delle icone nel KDE Plasma

### ISSUE THREAD

**Issue by gusbemacbe** [Magog64/SURU-PLUS#8]
Ciao Andrea,

Andiamo risolvere i bug delle icone nel KDE Plasma. 

L'icona di Mailspring va bene nel pannello del KDE:

![mailspring nel pannello](https://user-images.githubusercontent.com/2257024/40209077-c6b85240-5a13-11e8-8302-69f73bcf1059.png)

Ma non nel launcher/launchpad di apps, anche coll'icona Thunderbird:

![mailspring e thunderbird nel launcher](https://user-images.githubusercontent.com/2257024/40209115-ee5eff60-5a13-11e8-8625-72c7cedc097c.png)

Purtroppo, le icone di selettore di colore ancora non hanno migliorato, eccole:

![icone di selettori di colore](https://user-images.githubusercontent.com/2257024/40209173-3922c180-5a14-11e8-8c2f-4ec04709079c.png)

L'icona di Firefox va bene nel grande schermo, ma non nel piccolo schermo:

![firefox](https://user-images.githubusercontent.com/2257024/40209239-7ee9ac24-5a14-11e8-9ea6-74542807f022.png)

Anche coll'icona apt-url.svg:

![apt-url](https://user-images.githubusercontent.com/2257024/40209299-c6eeb5e6-5a14-11e8-8b8b-6469a176cfeb.png)

Io ti suggero di copiare le icone compatibili col KDE Plasma per sostituire le icone buggate di apt-url, Firefox, Mailspring, Thunderbird e selettori di colore.

**Comment by gusbemacbe** [comment]
Anche vedi le icone:

L'icona di galleria di foti e le icone di foti ed immagine:

![image](https://user-images.githubusercontent.com/2257024/40210883-db026d62-5a1d-11e8-93d5-03a90c3ea3bb.png)

Google Maps:

![image](https://user-images.githubusercontent.com/2257024/40210924-06dd8034-5a1e-11e8-988b-968a0bb48c20.png)

Goa e Google Earth:

![image](https://user-images.githubusercontent.com/2257024/40210975-4722f868-5a1e-11e8-90f7-a746cefa5905.png)

Ice*:

![image](https://user-images.githubusercontent.com/2257024/40210995-5eeda2e0-5a1e-11e8-97a4-a5eda9d7648a.png)

Kali Arping (io ti suggero di copiare l'icona di Kali Volatilità che funziona molto bene nel KDE per tutte le icone con un mappa:

![image](https://user-images.githubusercontent.com/2257024/40211036-8e3991d0-5a1e-11e8-98b4-526a8a7b40a6.png)

Tutte le icone di geo-localizzazione e mappa:

![image](https://user-images.githubusercontent.com/2257024/40211060-b8c8e856-5a1e-11e8-8d2e-2d27a529bb82.png)

Vivaldi unziona perfettamente nel KDE, perciò, è utile per sostituire le icone buggate:

![image](https://user-images.githubusercontent.com/2257024/40211099-0a079672-5a1f-11e8-8898-140954a89232.png)

**Comment by gusbemacbe** [comment]
@Magog64, come io ti avevo detto in Hangouts, ti suggerisco di disegnare da zero in puro SVG senza contenere l'immagine PNG. Sai fare ciò?

**Comment by Magog64** [comment]
Fixed icon:
applications-graphics
apt-url
credentials-preferences
crossftp
cs-color
cs-network
deepin-picker
emblem-mail
evolution
firefox
gallery-app
gcolor
geary
gnome-color-manager
gnome-maps
gnome-photos
goa-panel
google-earth
googleearth
gpaint
gpick
gthumb
icecat
iceweasel
internet-mail
kali-arping
kcolorchooser
kgeography
kmail
logo_big
logo
mail-app
mailspring
maps-app
mark-location-symbolic
mate-network-properties
multimedia-photo-manager
multimedia-photo-viewer
network-wireless
network-workgroup
nm-device-wireless
org.gnome.Evolution
org.gnome.Maps
org.gnome.Photos
pinta
preferences-color
preferences-system-network
preferences-system-sharing
sylpheed
thunderbird
unity-color-panel
unity-lens-photos
vpn

**Comment by Magog64** [comment]
Added icons
franz 
kcalc 
kclock 
kdeapp 
kde-frameworks 
kde-gtk-config 
kde-im-log-viewer 
kdevelop 
krename 
ktorrent 
kuser 
planetkde 
ring-kde
telepathy-kde 
ubiquity-kde 
usb-creator-kde

**Comment by gusbemacbe** [comment]
Io le ho testate nel KDE, tutto va molto bene, ma solamente le icone di Deepin Picker e Kvanum non vanno bene perché loro utilizzano le imagine PNG.

**Comment by Magog64** [comment]
Added icons:
applications-multimedia
calamares
calligrasheets
calligrawords
fluid
git-cola
im.vector
internet-telephony
kaffeine
kalgebrabackend
kalgebra
kamoso
kchart
kdiamond
kile
kipi-panorama
kiriki
kjumpingcube
kleopatra
kmenuedit
kmousetool
knotes
kolourpaint
kpat
kspread
ktnef
kube-mail
kword
mail-client
photolayoutseditor
plasma-media-center
plasma-mobile-phone
preferences-desktop-font-installer
ruby
sheets
subtitlecomposer
systemsettings
utilities-energy-monitor
word

Improved icons in mimetypes
text-x-bibtex
text-x-tex

**Comment by Magog64** [comment]
Added icons

apper
artikulate
blogilo
breeze-settings
calligrastage
claws-mail
cuttlefish
freemind
hotspot
imagewriter
kanagram
kblogger
keepass2
keepass
klines
kolf
korg-todo
kpresenter
kronometer
ktimer
kwrite
lastpass
masterpdfeditor
matlab
mendeleydesktop
muon
picmi
q4wine
rekonq
ring
rosegarden
sage-notebook
smtube
stage

**Comment by Magog64** [comment]
Added icons:

bittorrent-sync
calibre-ebook-edit
calibre-viewer
converseen
homerun
katomic
kblocks
kfind
kget
kmag
kmouth
knetattach
konversation
krdc
krfb
kruler
ktip
qelectrotech
quassel
qupzilla
skanlite
sweeper
umbrello
yakuake
yandex-browser
