### ISSUE TITLE
Le icone di KDE

### ISSUE THREAD

**Issue by gusbemacbe** [Magog64/SURU-PLUS#8]
Ciao Andrea,

Ci sono molte icone di KDE nel tuo repositorio. Come il tuo repositorio è progettato solamente per l'Ubuntu, elimina le icone de KDE. UBuntu utilizza solamente il GNOME. 

Gustavo

**Comment by Magog64** [comment]
alcune sono di programmi che uso anche io

**Comment by gusbemacbe** [comment]
OK, Andrea. 

Solo un suggerimento. Non utilizzare più `ln -sf` perché lui crea il cammino absoluto. Utilizza `ln -sfnr` che crea il cammino relativo.

Io ho problema col mio nuovo repositorio. Io devo fare una grande pulizia di più di 3 mille symlink.

**Comment by Magog64** [comment]
ok
