### ISSUE TITLE
Due icone di mimetype

### ISSUE THREAD

**Issue by gusbemacbe** [Magog64/SURU-PLUS#9]
Ciao Andrea,

Buono pomeriggio!

Per favore, aggiungi due icone di mimetype per i file nel formato *.pub:

* `application-vnd.ms-publisher`
* `vnd.ms-publisher`

È un formato di certificado di chiave pubblica. 

Utilizziamo più questo sull'Ubuntu per caricare nostri repositori per Launchpad d'Ubuntu.

**Comment by gusbemacbe** [comment]
Non ti dimenticare di leggere i miei messagi sul Hangouts (Gmail).

**Comment by Magog64** [comment]
Fatte
